
version: '3.8'

services:
  service-registry:
    image: nigglenandu/service-reg
    container_name: service-reg
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - mysql
    networks:
      - fintech

  account-service:
    image: nigglenandu/account-management-service
    container_name: account-management-service
    restart: always
    environment:
      SPRING_APPLICATION_NAME: Account-Management-Service
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/accountmanagementservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18@13sql
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-reg:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - mysql
    networks:
      - fintech

  fund-service:
    image: nigglenandu/fund-transfer-service
    container_name: fund-transfer-service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - service-registry
      - mysql
    networks:
      - fintech
    environment:
      SPRING_APPLICATION_NAME: Fund-Transfer-Service
      SERVER_PORT: 8081
      ACCOUNT_MANAGEMENT_SERVICE_URL: http://account-management-service:8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fundtransferservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18@13sql
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-reg:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"

  transaction-service:
    image: nigglenandu/transaction-history-service
    container_name: transaction-history-service
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - service-registry
      - mysql
    networks:
      - fintech
    environment:
      SPRING_APPLICATION_NAME: Transaction-History-Service
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loantransferservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18@13sql
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-reg:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"

  loan-service:
    image: nigglenandu/loan-transfer-service
    container_name: loan-service
    ports:
      - "8084:8084"
    restart: always
    depends_on:
      - service-registry
      - mysql
    networks:
      - fintech
    environment:
      SPRING_APPLICATION_NAME: Transaction-History-Service
      SERVER_PORT: 8084
      ACCOUNT_MANAGEMENT_SERVICE_URL: http://account-management-service:8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transactionhistory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18@13sql
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-reg:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 18@13sql
    ports:
       - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fintech

volumes:
  mysql_data:

networks:
  fintech:
    driver: bridge

