version: '3.8'

services:
  service-registry:
    image: nigglenandu/service-reg
    container_name: service-reg
    ports:
      - "8761:8761"
    restart: always
    networks:
      - fintech-net

  account-service:
    image: nigglenandu/account-management-service
    container_name: account-management-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - service-registry
    networks:
      - fintech-net
    environment:
      SPRING_APPLICATION_NAME: Account-Management-Service
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/accountmanagementservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18@13sql
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-reg:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"

  fund-service:
    image: nigglenandu/fund-transfer-service
    container_name: fund-transfer-service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - service-registry
    networks:
      - fintech-net
    environment:
      SPRING_APPLICATION_NAME: Fund-Transfer-Service
      ACCOUNT_MANAGEMENT_SERVICE_URL: http://account-management-service:8080
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fundtransferservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18@13sql
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-reg:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: true
      EUREKA_CLIENT_FETCH_REGISTRY: true

networks:
  fintech-net:
    driver: bridge
